---
- name: Configure Calibre using Podman on Rocky Linux
  hosts: calibre_server
  remote_user: root
  become: true
  vars:
    calibre_container_name: calibre
    calibre_image: docker.io/lacusch/calibre-server:0.1
    calibre_library_dir: /root/Calibre-Libary
    calibre_port: 80
    timezone: "Europe/Berlin"
  tasks:
    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - podman
          - python3-podman
        state: present
        update_cache: true

    - name: Pull Calibre Docker image
      containers.podman.podman_image:
        name: "{{ calibre_image }}"
        state: present
    - name: Copy example library to remote server
      ansible.builtin.copy:
        src: ../books/Calibre-Libary
        dest: /root
        owner: root
        group: root
        mode: "0755"
        backup: true
    - name: Create systemd service file for Calibre container
      ansible.builtin.copy:
        dest: /etc/systemd/system/calibre-container.service
        owner: root
        group: root
        mode: "0644"
        content: |
          [Unit]
          Description=Calibre Content Server container
          After=network.target

          [Service]
          Restart=always
          ExecStart=/usr/bin/podman run --rm --name {{ calibre_container_name }} \
            -p {{ calibre_port }}:8080 \
            -v {{ calibre_library_dir }}:/etc/calibre/library \
            {{ calibre_image }} \
            /usr/bin/calibre-server /etc/calibre/library
          ExecStop=/usr/bin/podman stop -t 10 {{ calibre_container_name }}
          ExecStopPost=/usr/bin/podman rm -f {{ calibre_container_name }}

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Calibre container service
      ansible.builtin.systemd:
        name: calibre-container.service
        enabled: true
        state: started
        daemon_reload: true
