---
- name: Install packages
  hosts: all
  become: true
  vars:
    packages:
      - podman
      # - podman-compose
      # - buildah
      # - skopeo
      # - crun

  tasks:
    - name: Update system packages
      ansible.builtin.dnf:
        state: present
        update_cache: true
      tags: update
    - name: Install Packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
    - name: Install dnf-plugins-core (includes dnf copr command)
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Enable Caddy COPR repository
      ansible.builtin.command: dnf copr enable -y @caddy/caddy
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:group_caddy:caddy.repo

    - name: Install Caddy
      ansible.builtin.dnf:
        name: caddy
        state: present

    - name: Create Caddy directories (ensure proper ownership)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: caddy
        group: caddy
        mode: "0755"
      loop:
        - /etc/caddy
        - /var/lib/caddy
        - /var/log/caddy

    - name: Create basic Caddyfile
      ansible.builtin.copy:
        content: |
          # Basic Caddyfile
          # Replace with your domain and configuration
          :80 {
              respond "Hello from Caddy on AlmaLinux! test 123"
          }

          # Example with automatic HTTPS:
          # your-domain.com {
          #     root * /var/www/html
          #     file_server
          # }
        dest: /etc/caddy/Caddyfile
        owner: caddy
        group: caddy
        mode: "0644"
      notify: Restart caddy

    - name: Enable and start Caddy service
      ansible.builtin.systemd:
        name: caddy
        enabled: true
        state: started
        daemon_reload: true

    - name: Open firewall for HTTP (port 80)
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Open firewall for HTTPS (port 443)
      ansible.posix.firewalld:
        port: 443/tcp
        permanent: true
        state: enabled
        immediate: true

    - name: Show installation result
      ansible.builtin.debug:
        msg:
          - "Caddy installation completed!"
          - "Service status: {{ caddy_status.stdout }}"
          - "Edit /etc/caddy/Caddyfile to configure your sites"
          - "Use 'sudo systemctl reload caddy' after configuration changes"

  handlers:
    - name: Restart caddy
      ansible.builtin.systemd:
        name: caddy
        state: restarted
